print("my name is %s"%"dileep","i am %d year old"%32)
print("%6.3f"%(3.12345))
print("hai my name is {} am {} year old".format("dileep","32"))
print("hai my name is {0} am {1} year old".format("dileep","32"))
print("hai my name is {name} am {age} year old".format(name="dileep",age="32"))
print(format(1.234,"6.3f"))
a='dileep'
b=32
print(f"hai my name is {a} am {b} year old")
print("%6.3f"%(3.456489))
print(format(3.45677,"0.3f"))
print('hai hello how are you'.split('how'))
print(",".join("hai hello"))
a='hai hello how are you well ou ai'
print(f"hai {a} are you {a.upper()}")
print(bool('235'))
print(a.rindex('ai'))
print(a.rfind('o'))
print(a.count('ou'))
print(a[-2:-5])